package com.arsildo.merr_patenten.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4E57A9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDFE0FF)
val md_theme_light_onPrimaryContainer = Color(0xFF010965)
val md_theme_light_secondary = Color(0xFF1C60A5)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD4E3FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001C3A)
val md_theme_light_tertiary = Color(0xFFBF0027)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD8)
val md_theme_light_onTertiaryContainer = Color(0xFF410007)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_outline = Color(0xFF777680)
val md_theme_light_inverseOnSurface = Color(0xFFF3F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFBDC2FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4E57A9)
val md_theme_light_outlineVariant = Color(0xFFC7C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFBDC2FF)
val md_theme_dark_onPrimary = Color(0xFF1D2678)
val md_theme_dark_primaryContainer = Color(0xFF353E90)
val md_theme_dark_onPrimaryContainer = Color(0xFFDFE0FF)
val md_theme_dark_secondary = Color(0xFFA4C8FF)
val md_theme_dark_onSecondary = Color(0xFF00315D)
val md_theme_dark_secondaryContainer = Color(0xFF004784)
val md_theme_dark_onSecondaryContainer = Color(0xFFD4E3FF)
val md_theme_dark_tertiary = Color(0xFFFFB3B1)
val md_theme_dark_onTertiary = Color(0xFF680011)
val md_theme_dark_tertiaryContainer = Color(0xFF92001C)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE4E1E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE4E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val md_theme_dark_outline = Color(0xFF91909A)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE4E1E6)
val md_theme_dark_inversePrimary = Color(0xFF4E57A9)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFBDC2FF)
val md_theme_dark_outlineVariant = Color(0xFF46464F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF2B2D42)


val PrussianBlue = Color(0xFF014575)
val DarkSpringGreen = Color(0xFF1E8F50)
val OffWhite = Color(0xFFFDFCFE)
val OffBlack = Color(0xFF141413)
val White = Color(0xFFFFFFFF)
val Black = Color(0xFF000000)

val GrayedOot = Color(0xFFD5D5D5)
val Red = Color(0xFFB40202)
val Green = Color(0xFF09BB10)