name: JVM CI

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'iosApp/**'
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.editorconfig'
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - 'iosApp/**'
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.editorconfig'
  workflow_dispatch:

jobs:
  build:
    name: Build & Test (JVM)
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=512m" -Dkotlin.compiler.execution.strategy="in-process" -Dorg.gradle.workers.max=2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew

      - name: Build and Test JVM
        run: ./gradlew :desktopApp:jar jvmTest
